<?php
/*
	This file inserts all of the ingredients that can be used in recipes
	Each ingredient is a row in the MasterIngredients table
	
	The name of each ingredient can't be NULL (but can be a string that has the letters 'NULL'
	and must be unique
*/

include 'cooked_funcs.php';

// sql code to create ingredients table
ExecuteSQL($conn,
	"CREATE TABLE MasterIngredientList(
    id INT(4)  primary key auto_increment, 
	name VARCHAR(128) NOT NULL UNIQUE
	)");

// sql code to add ingredients to table
ExecuteSQL($conn,
	"INSERT INTO MasterIngredientList (name)
	VALUES
	('NULL'),
	('00 Flour'),
	('AP Flour'),
	('Allspice'),
	('Angel Hair Pasta'),
	('Bacon'),
	('Baking Powder'),
	('Baking Soda'),
	('Bay Leaf'),
	('Blueberries'),
	('Bread Flour'),
	('Brown Sugar'),
	('Butter'),
	('Buttermilk'),
	('Curry Powder'),
	('Cake Flour'),
	('Celery'),
	('Chicken Breasts'),
	('Chicken Broth'),
	('Chicken Thighs'),
	('Cider Vinegar'),
	('Cinnamon'),
	('Cocoa Powder'),
	('Condensed Milk'),
	('Cornstarch'),
	('Cream Cheese'),
	('Dark Brown Sugar'),
	('Dark Molasses'),
	('Diastatic Malt Powder'),
	('Dijon Mustard'),
	('Distilled White Vinegar'),
	('Dried Basil'),
	('Dried Chili Powder'),
	('Dried Oregano'),
	('Dried Parsley'),
	('Dried Rosemary'),
	('Dried Thyme'),
	('Dry Sherry'),
	('Egg'),
	('Eggs'),
	('Egg Whites'),
	('Egg Yolks'),
	('Fresh Parsley'),
	('Fresh Rosemary'),
	('Fresh Thyme'),
	('Fried Onions'),
	('Garlic'),
	('Garlic Powder'),
	('Gelatin'),
	('Ginger'),
	('Ginger Powder'),
	('Green Beans'),
	('Ground Beef'),
	('Ground Chuck'),
	('Ground Corriander'),
	('Ground Pork'),
	('Ground Sirloin'),
	('Half and Half'),
	('Hazelnut Oil'),
	('Hazelnuts'),
	('Heavy Cream'),
	('High Gluten Flour'),
	('Honey'),
	('Hot Sauce'),
	('Ketchup'),
	('Kosher Salt'),
	('Lemon Juice'),
	('Lemon Zest'),
	('Mace'),
	('Milk'),
	('Non-diastatic Malt Powder'),
	('Molasses'),
	('Monterey Cheese'),
	('Mustard'),
	('Olive Oil'),
	('Onion'),
	('Onion Powder'),
	('Paprika'),
	('Parmesan Cheese'),
	('Parsley'),
	('Pastry Flour'),
	('Pepper'),
	('Pork Butt'),
	('Pork Rub'),
	('Potatoes'),
	('Powdered Sugar'),
	('Red Pepper Flakes'),
	('Red POtatoes'),
	('Rosemary Powder'),
	('Rye Flour'),
	('Salt'),
	('Saltines'),
	('Sandwich Bread'),
	('Sausage'),
	('Skim Milk'),
	('Sour Cream'),
	('Soy Sauce'),
	('Steak Sauce'),
	('Subgroup'),
	('Sugar'),
	('Tomatoes'),
	('Tomato Juice'),
	('Tomato Paste'),
	('Unsalted Butter'),
	('Vanilla Bean'),
	('Vanilla Extract'),
	('Vegetable Oil'),
	('Water'),
	('White Mushrooms'),
	('White Vinegar'),
	('Whole Milk'),
	('Whole Wheat Flour'),
	('Worcestershire Sauce'),
	('Yeast'),
	('Yogurt Culture')
	;");

?>
