<?php
/*
	This file inserts all of the ingredients that can be used in recipes
	Each ingredient is a row in the MasterIngredients table
	
	The name of each ingredient can't be NULL (but can be a string that has the letters 'NULL'
	and must be unique
*/

include 'cooked_funcs.php';

// sql code to create ingredients table
// each ingredient has CALORIES per UNIT amount
// tsp is the number of grams per tsp of this ingredient
ExecuteSQL($conn,
	"CREATE TABLE MasterIngredientList(
    id INT(4)  primary key auto_increment, 
	name VARCHAR(128) NOT NULL UNIQUE,
	unit VARCHAR(128) NOT NULL,
	calories DECIMAL(10,5) NOT NULL
	)");

// sql code to add ingredients to table
// calories are per the unit values. For example, AP Flour is 3.6330 calories/gram
// tsp is tsp per unit weight. For example, AP Flour is 2.6041 tsp per gram
ExecuteSQL($conn,
	"INSERT INTO MasterIngredientList (name, unit, calories)
	VALUES
	('NULL',                  'g', 		0.0000),
	('00 Flour',              'g', 		3.5980),
	('Active Dry Yeast',      'g', 		1.0582),
	('AP Flour',              'g', 		3.6330),
	('Allspice',              'tsp',	5.0000),
	('Almond Flour',          'g', 		0.0000),
	('American Cheese',       'oz', 	105.00),
	('Angel Hair Pasta',      'g', 		3.5630),
	('Apples',   			  'g', 		0.5200),
	('Apple Cider Vinegar',   'g', 		0.2000),
	('Apricot Preserves',     'g', 		0.0000),
	('Arbol Chilis',          'g', 		0.0000),
	('Arbol Chili Seeds',     'g', 		0.0000),
	('Baby Spinach',       	  'cup',	0.0000),
	('Baby Bella Mushrooms',  'lb', 	30),
	('Bacon',           	  'ea',		45.000),
	('Baking Powder',         'tsp',	2.0000),
	('Baking Soda',           'tsp',  	0),
	('Bay Leaf',              'ea', 	0.6000),
	('Black Cocoa Powder',    'g', 		2.0000),
	('Blueberries',           'g', 		0.5644),
	('Bourbon',           	  'cup',	0.00),
	('Bran Chex',             'g', 		3.4216),
	('Bread Flour',           'g', 		3.6085),
	('Broccoli',              'g',		0.3527),
	('Brown Rice Flour',      'g', 		0.0000),
	('Brown Sugar',           'g', 		3.7038),
	('Butter',                'cup',	1630),
	('Buttermilk',            'g', 		0.3880),
	('Cake Batter Extract',   'g', 		0.0000),
	('Cake Flour',            'g', 		2.9630),
	('Canola Oil',            'g', 		8.8185),
	('Carrot',                'ea',		25.000),
	('Celery',                'rib',	12.000),
	('Celery Stalk',          'ea', 	12.000),
	('Cheddar Cheese',        'g', 		3.9286),
	('Chicken Breasts',       'g', 		2.3986),
	('Chicken Broth',         'oz', 	1.25),
	('Chicken Thighs Boneless', 'lb',	640),
	('Chicken Thighs Bone In', 'lb', 	960),
	('Chocolate Chips',       'tbsp', 	70),
	('Cider Vinegar',         'g', 		0.2116),
	('Cilantro',              'g', 		0.0000),
	('Cinnamon',              'g', 		2.4339),
	('Cocoa Powder',          'g', 		2.2222),
	('Condensed Milk',        'g', 		3.2099),
	('Corn Chex',             'g', 		3.85),
	('Corn Syrup',            'g', 		2.8571),
	('Cornstarch',            'tbsp', 	31),
	('Cream Cheese',          'g', 		3.4216),
	('Crisco',                'g', 		9.1667),
	('Curry Powder',          'g', 		3.3158),
	('Dark Brown Sugar',      'g', 		3.7743),
	('Dark Molasses',         'g', 		2.8925),
	('Dark Soy Sauce',        'tsp', 	8),
	('Diastatic Malt Powder', 'g', 		3.0688),
	('Dijon Mustard',         'tsp', 	4),
	('Distilled White Vinegar','g', 	0.1764),
	('Dried Basil',           'g', 		2.5045),
	('Dried Chili Powder',    'g',  	2.7514),
	('Dried Oregano',         'g',  	3.5400),
	('Dried Parsley',         'tsp', 	2),
	('Dried Rosemary',        'tsp', 	4),
	('Dried Thyme',           'tsp', 	3),
	('Dry Sherry',            'g',   	1.5873),
	('Egg',                   'ea',  	1.5873),
	('Eggs',                  'ea',  	1.5873),
	('Egg Whites',            'ea',  	17),
	('Egg Yolks',             'g',   	3.2452),
	('Elbow Macaroni',        'g',   	3.57142),
	('Fresh Parsley',         'tsp', 	1),
	('Fresh Rosemary',        'tsp', 	1),
	('Fresh Thyme',           'tsp', 	1),
	('French Bread',          'g', 		2.7514),
	('Fried Onions',          'g', 		2.5750),
	('Frozen Peas',           'cup', 	118),
	('Garlic',                'clove', 	4),
	('Garlic Powder',         'tsp', 	10),
	('Gelatin',               'tsp', 	3),
	('Ginger',                'g', 		0.8113),
	('Ginger Powder',         'tsp', 	6.25),
	('Green Beans',           'g', 		0.3175),
	('Green Bell Pepper',     'g', 		0.2116),
	('Ground Beef',           'g', 		3.3158),
	('Ground Chuck',          'g', 		2.5574),
	('Ground Coriander',      'tsp', 	5),
	('Ground Pork',           'g', 		2.3986),
	('Ground Pork Sausage',   'g', 		3.0336),
	('Ground Sirloin',        'g', 		2.4339),
	('Half and Half',         'g', 		1.3051),
	('Ham',                   'g', 1.4462),
	('Hazelnut Oil',          'g', 8.8538),
	('Hazelnuts',             'g', 6.2788),
	('Heavy Cream',           'g', 3.6332),
	('High Gluten Flour',     'g', 3.4900),
	('Honey',                 'g', 3.0336),
	('Hot Sauce',             'tsp', 0.0000),
	('Ice Cubes',             'g', 0.0000),
	('Italian Seasoning',     'g', 0.0000),
	('Ketchup',               'g', 1.1288),
	('Kosher Salt',           'g', 0.0000),
	('Lemon Juice',           'g', 0.2116),
	('Lemon Zest',            'g', 0.2116),
	('Liquid Stevia',         'g', 0.0000),
	('Mace',                  'g', 8),
	('Marachino Cherry',      'g', 1.5873),
	('Meathead\'s Memphis Dust', 'g', 1.6932),
	('Milk',                  'g', 0.4232),
	('Millet Flour',          'g', 0.0), 
	('Minced Fresh Parsley',  'tsp', 1),
	('Molasses',              'g', 2.8925),
	('Monterey Cheese',       'oz',106),
	('Mozzarella Cheese',     'oz', 79),
	('Mustard',               'g', 0.5997),
	('Non-diastatic Malt Powder', 'tsp', 10),
	('Nutmeg',				  'tsp', 11),
	('Olive Oil',             'tbsp', 120),
	('Onion',                 'ea', 44),
	('Onion Powder',          'tsp', 8),
	('Oreos',                 'g', 4.7058),
	('Paprika',               'tsp', 6),
	('Parmesan Cheese',       'oz', 122),
	('Parsley',               'tsp', 1),
	('Pastry Flour',          'g', 3.6332),
	('Peaches',               'g', 0),
	('Pepper',                'tsp', 6),
	('Peppermint Bark',       'g', 4.9384),
	('Peppermint Extract',    'g', 2.8571),
	('Pistachios',    		  'g', 0.0),
	('Pork Butt',             'g', 2.6808),
	('Pork Loin',             'g', 2.4339),
	('Pork Rub',              'g', 1.6932),
	('Potatoes',              'lb', 440),
	('Potato Starch',         'g', 0.0),
	('Powdered Sugar',        'g', 3.8801),
	('Prime Rib Roast',       'ea', 1),
	('Psyllium Husk Powder',  'g', 0.0),
	('Pumpkin Pie Spice',  	  'g', 0.0),
	('Pumpkin Puree',    	  'g', 0.0),
	('Quinoa Flour',          'g', 0.0),
	('Red Bell Pepper',       'g', 0.3175),
	('Red Food Coloring',     'g', 0.0000),
	('Red Pepper Flakes',     'g', 0.2000),
	('Red Potatoes',          'lb', 319),
	('Rice Chex',             'g', 4),
	('Rice Vinegar',          'g', 0.1812),
	('Roasted Unsalted Peanuts', 'g', 5.671),
	('Rosemary Powder',       'tsp', 4),
	('Rye Flour',             'g', 3.4921),
	('Salt',                  'tsp', 0.00),
	('Saltines',              'g', 4.2329),
	('Sandwich Bread',        'g', 2.6455),
	('Sausage',               'g', 3.0336),
	('Scallion',              'g', 0.3175),
	('Seasoning Salt',        'g', 0.0000),
	('Shaoxing Wine',         'g', 1),
	('Sesame Oil',            'g', 8.8185),
	('Shortening',            'g', 9.1667),
	('Skim Milk',             'g', 0.3880),
	('Sour Cream',            'g', 1.9048),
	('Soy Sauce',             'tbsp', 9),
	('Sprinkles',             'g', 5.0089),
	('Steak Sauce',           'g', 0.9524),
	('Subgroup',              'g', 0.000000),
	('Sugar',                 'g', 3.9154),
	('Sun Dried Tomatoes',    'g', 4.66667),
	('Superfine Brown Rice Flour', 'g', 0.0),
	('Tapioca Starch',        'g', 0.0),
	('Toasted Sesame Oil',    'g', 8.8538),
	('Tomatoes',              'g', 0.1764),
	('Tomato Juice',          'g', 0.1764),
	('Tomato Paste',          'g', 0.8113),
	('Unsalted Butter',       'tbsp', 102),
	('Unsweetened Vanilla Almond Milk', 'g', 0.1235),
	('Vanilla Bean',          'g', 2.9277),
	('Vanilla Extract',       'tbsp', 38),
	('Vanilla Ice Cream',     'g', 2.0811),
	('Vanilla Protein Powder','g', 4.0212),
	('Vegetable Oil',         'tbsp', 120),
	('Vodka',                 'tsp', 10.666),
	('Water',                 'g', 0.0),
	('Wheat Chex',            'g', 3.4569),
	('Whipped Cream',         'g', 3.4569),
	('White Mushrooms',       'lb', 101),
	('White Pepper',          'g', 2.9630),
	('White Rice', 	          'cup', 0.0),
	('White Vinegar',         'g', 0.1764),
	('White Wine', 	          'g', 0.0000),
	('Whole Milk',            'g', 0.5997),
	('Whole Milk Yogurt',     'g', 0.0000),
	('Whole Wheat Flour',     'g', 3.3863),
	('Worcestershire Sauce',  'tbsp', 13),
	('Xanthan Gum',           'g', 3.3158),
	('Yeast',                 'tsp', 12),
	('Yogurt Culture',        'g', 0.5997),
	('Yellow Bell Pepper',    'g', 0.2822)
	;");
?>
